### PR TITLE
Removed comment

### PR DESCRIPTION
**Pull request by HUSKUT**

### CODE REVIEW

**Review by SophiaH67 — CHANGES_REQUESTED** [review]
~~Hmm, getting mixed signals here. Might not be good to remove documentation~~

This commit looks good to me!

**Review by ACodingPhoenix — CHANGES_REQUESTED** [review]
Why didn't you sign this commit?

**Comment by HUSKUT** [comment]
> Why didn't you sign this commit?

cry

**Comment by ACodingPhoenix** [comment]
~~edited co-workers comment, chris kinda sus~~

I approve

**Pull request merged**
